### ISSUE TITLE
Stream Deck + not working at all - Anyone else with M1 Silicone have this issue?

### ISSUE THREAD

**Issue by ThunderJump512** [GenericMale/streamdeck-sonos#14]
It was very easy to download and install plugin. I am also able to add Sonos buttons and the ip addess for my Sonos Amp via the Elgato app for Stream Deck +. But when I try to use plugin the buttons light up with a yellow triangle/exclamation point icon.  

Wondering if issue is that I am using M1 Macbook pro, or maybe plugin doesn't work with Sonos Amps?

Any assistance or advice would be much appreciated!

**Comment by Thornic** [comment]
Having the same issue on a Windows 10 PC

**Comment by Thornic** [comment]
I fixed it. If you let the sonos speaker play a song first, and then press the buttons on the steamdeck. It connects and work.

**Comment by fractically** [comment]
Not sure if there was a bug causing this and that bug has been reintroduced since @Thornic's post, but I just downloaded/installed/set it up for the first time (on an M2 Mac using a Stream Deck+) and I'm having the same issue as the OP (and yes, it's still happening after playing a song). All of my devices are still on the S1 (old) Sonos platform - is this plugin only compatible with S2 systems, and if so, that should be documented somewhere.

**Comment by kylexrich** [comment]
Was upset to discover this limitation as well.
